---  
- name: Update & upgrade
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes

- name: Docker is present
  ansible.builtin.apt:
    name: docker
    state: present

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
