---  
- name: Update & upgrade
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes

- name: Docker is present
  ansible.builtin.apt:
    name: docker
    state: present

- name: Adding user {{ username }} to docker group 
  ansible.builtin.user: 
    name: '{{ username }}'
    groups: docker
    append: yes

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
