---
- name: Firewall ufw enabled
  community.general.ufw:
    state: "enabled"
    policy: "deny"
    logging: "on"

- name: Firewall limit ssh
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Firewall allow web ports
  community.general.ufw:
    rule: "allow"
    port: "{{ item }}"
    proto: "tcp"
  with_items:
    - "80"
    - "443"    
